version: '3.3'

services:
  bot:
    container_name: geo_bot
    image: geo_bot
    restart: unless-stopped
    user: "${UID}:${GID}"
    working_dir: /bot
    build: .
    env_file:
      - ./.env
    volumes:
      - ./:/bot
    command: python main.py

  db:
    container_name: db
    image: postgres:12.3
    restart: unless-stopped
    user: "${UID}:${GID}"
    env_file:
      - ./.env
    volumes:
      - ./data:/bot/data
      - ./data/db:/var/lib/postgresql/data
